const p = msg.payload;
const negar = motivo => [null, {topic: 'sim/decision_retencion', payload: {activar: false, motivo, solicitud_id: p && p.solicitud_id || null, run_id: p && p.run_id || 'desconocido', ts: new Date().toISOString(), sintetico: true}}];
if (!p || typeof p !== 'object' || Array.isArray(p)) return negar('solicitud inválida');
if (p.sintetico !== true) return negar('esta entrada solo admite pruebas controladas');
if (!/^\d{5}$/.test(String(p.veh || ''))) return negar('vehículo inválido');
if (typeof p.esperar_s !== 'number' || !Number.isFinite(p.esperar_s) || p.esperar_s <= 0 || p.esperar_s > 600) return negar('retención inválida');
if (typeof p.retraso_tren_s !== 'number' || !Number.isFinite(p.retraso_tren_s) || p.retraso_tren_s <= 240) return negar('el tren no supera cuatro minutos de retraso');
if (!p.run_id || !/^99\d{2}$/.test(String(p.oper || ''))) return negar('ensayo u operador simulado inválido');
const kpi = flow.get('sim_kpi_' + p.run_id);
if (!kpi || kpi.oper_sim !== p.oper || !Number.isFinite(kpi.irregularidad)) return negar('KPI ausente');
const edad = (Date.now() - Date.parse(kpi.ts)) / 1000;
if (!Number.isFinite(edad) || edad < -5 || edad > 60) return negar('KPI caducado');
if (kpi.irregularidad > 0.3) return negar('irregularidad superior a 0,3');
const used = flow.get('sim_solicitudes') || {};
if (!p.solicitud_id || used[p.solicitud_id]) return negar('solicitud sin identificador o repetida');
for (const [id, ts] of Object.entries(used)) if (Date.now() - ts > 3600000) delete used[id];
used[p.solicitud_id] = Date.now(); flow.set('sim_solicitudes', used);
const payload = {run_id: p.run_id, esperar_s: p.esperar_s, solicitud_id: p.solicitud_id, sintetico: true};
return [{topic: 'decision/retener/sim/' + p.oper + '/' + p.veh, payload, qos: 1, retain: false}, {topic: 'sim/decision_retencion', payload: {activar: true, motivo: 'tren retrasado y regularidad admisible', irregularidad: kpi.irregularidad, ...payload, ts: new Date().toISOString()}}];
