apiVersion: 1
datasources:
  - name: InfluxDB flota
    uid: influx-flota
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: lab
      defaultBucket: flota
    secureJsonData:
      token: ${INFLUX_TOKEN}
